apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btg-labware-result-api-service
    tags.datadoghq.com/env: uat
    tags.datadoghq.com/service: btg-labware-result-api-service
    tags.datadoghq.com/version: version
  name: btg-labware-result-api-service
  namespace: uat
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: btg-labware-result-api-service
  template:
    metadata:
      annotations:
        ad.datadoghq.com/btg-labware-result-api-service.logs: '[{"service":"btg-labware-result-api-service","tags":["env:uat"]}]'
        admission.datadoghq.com/js-lib.version: v5.28.0
      labels:
        admission.datadoghq.com/enabled: "true"
        app: btg-labware-result-api-service
        tags.datadoghq.com/env: uat
        tags.datadoghq.com/service: btg-labware-result-api-service
        tags.datadoghq.com/version: version
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-map-microplate-result-api-service-uat
        - secretRef:
            name: infra
        - secretRef:
            name: secrets-microplate-result-api-service-uat
        image: asia-southeast1-docker.pkg.uat/app-nonprod-project/app-nonprod-ar/btg-labware-result-api-service:uat-b6d1ca86ddd80e65e8faaf8aa9f3e57828b0ef6a
        imagePullPolicy: Always
        name: btg-labware-result-api-service
        ports:
        - containerPort: 6404
          name: http
          protocol: TCP
        # Change resources section according to your project needed
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          allowPrivilegeEscalation: false
