apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btg-labware-vision-worker
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: btg-labware-vision-worker
    tags.datadoghq.com/version: version
  name: btg-labware-vision-worker
  namespace: dev
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: btg-labware-vision-worker
  template:
    metadata:
      annotations:
        ad.datadoghq.com/btg-labware-vision-worker.logs: '[{"service":"btg-labware-vision-worker","tags":["env:dev"]}]'
      labels:
        admission.datadoghq.com/enabled: "true"
        app: btg-labware-vision-worker
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: btg-labware-vision-worker
        tags.datadoghq.com/version: version
    spec:
      # Force all pods using same PVC to schedule on same node (required for ReadWriteOnce)
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - btg-labware-image-ingestion-service
            topologyKey: kubernetes.io/hostname
      containers:
      - name: btg-labware-vision-worker
        image: asia-southeast1-docker.pkg.dev/app-nonprod-project/app-nonprod-ar/btg-labware-vision-worker:dev-c42e5fede8199de2f9d318da2d1b8269b58087be
        imagePullPolicy: Always
        command: ["python", "worker.py"]
        envFrom:
        - configMapRef:
            name: config-map-microplate-vision-inference-service-dev
        - secretRef:
            name: infra
        - secretRef:
            name: secrets-microplate-vision-inference-service-dev
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: storage
          mountPath: /mnt/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc-labware-dev
